export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED'
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED'
export const LOAD_PROFILE = 'LOAD_PROFILE'
export const LOAD_HOME_TAGS = 'LOAD_HOME_TAGS'
export const LOAD_HOME_BY_TAG = 'LOAD_HOME_BY_TAG'

export const CHANGE_USERNAME = 'CHANGE_USERNAME' 
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD' 
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const LOGIN_EMAIL = 'LOGIN_EMAIL'
export const LOGIN_PASSWORD = 'LOGIN_PASSWORD'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS' 
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SETTINGS_LOGOUT = 'SETTINGS_LOGOUT'
export const SETTINGS_INPUT = 'SETTINGS_INPUT'
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS'
export const SETTINGS_FAIL = 'SETTINGS_FAIL'

export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'